sudo: required
services:
  - docker # installs a copy of docker

# Commands ran before the test run
before_install:
  - docker build -t jerlam06/docker-react -f Dockerfile.dev .

# Ran when our test needs to be executed
script:
  - docker run jerlam06/docker-react npm run test -- --watchAll=false
